pub mod analyzer;
pub mod symbol_table;
mod operator_table;
mod mangling;
pub mod type_registry;
mod method_transforms;
mod type_resolution;
mod constant_folding;
mod type_duplicator;
mod generic_helper;
mod generic_fixer;
mod top_level_collector;